### ISSUE TITLE
Stuck on "Latest API meta-data loaded! You may begin."

### ISSUE THREAD

**Issue by hearsid** [addypy/datagovindia#3]
The script gets stuck on the step when I try to initialize using `DataGovIndia(API_KEY)` on second step, _"Latest_ API meta-data loaded! You may begin."
![image](https://user-images.githubusercontent.com/3892451/162602819-ae2d511c-6111-4866-ab67-06c8b50c44cc.png)
```
from datagovindia import DataGovIndia
import streamlit as st

@st.cache(suppress_st_warning=True)
def getDataGovAdaptor(): 
    return DataGovIndia(API_KEY)

datagovin = getDataGovAdaptor()
result = datagovin.search(description="Wheat",max_results=1,print_results=True)
```

**Comment by addypy** [comment]
@hearsid 
I was able to reproduce this error. When you initializate the `DataGovIndia` class with your API_KEY, it downloads the latest meta-data (list of APIs, titles, description etc.) and stores it in memory. Since these are python objects, it is possible that the streamlit cache isn't able to store them.

However, I looked at their documentation, and I was able to make it work by adding an additional kwarg (`allow_output_mutation=True`) in the `@st.cache` decorator. 

This is what I used - 
```python
import os
from datagovindia import DataGovIndia
import streamlit as st
API_KEY = os.environ['DATAGOVIN_API_KEY']
@st.cache(allow_output_mutation=True,suppress_st_warning=True)
def getDataGovAdaptor(): 
    return DataGovIndia(API_KEY)

datagovin = getDataGovAdaptor()
result = datagovin.search(description="Wheat",max_results=1,print_results=True)
```
Here's the output:

![bug3](https://user-images.githubusercontent.com/54233083/162645035-2b5abc61-0c37-4e3f-b14d-79b6f86ae7e1.png)
 
 
 Hope this solves your issue!

**Comment by hearsid** [comment]
@addypy Thank you for the quick reply, it is working for the first time and then giving this error, 
![image](https://user-images.githubusercontent.com/3892451/162663606-7dd12799-530d-4a75-a9f1-fe53b494db4c.png)
I also think and agree that it may be because @st.cache is not able to store the DataGovIndia in memory, I'm also looking for other options to replicate st.cache functionality.

**Comment by addypy** [comment]
Not sure if this is useful, but if you can't find an alternative, you could try to wrap multiple arguments in the same function - initiate the class with your key, search for the results, and store the output you need. 
All the best!
